"""Add show_phone_number to User model again and remove it from car

Revision ID: 442637048b47
Revises: 4708f1c5572b
Create Date: 2025-09-15 21:12:23.098460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442637048b47'
down_revision: Union[str, Sequence[str], None] = '4708f1c5572b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'show_phone_number')
    op.add_column('users', sa.Column('show_phone_number', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'show_phone_number')
    op.add_column('cars', sa.Column('show_phone_number', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
    # ### end Alembic commands ###
