"""Add show_phone_number to User model

Revision ID: 4708f1c5572b
Revises: ae4bde31d950
Create Date: 2025-09-15 20:59:56.700858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4708f1c5572b'
down_revision: Union[str, Sequence[str], None] = 'ae4bde31d950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('show_phone_number', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'show_phone_number')
    # ### end Alembic commands ###
